Add syntaxes highlight: if/else, true/false, and/or and others
serkonda7/vscode-vba pull request #38
Opened 2022-04-04 05:00 UTC by bopoh13

Part first of two.
- Added 27 items highlighting for issue #36. For 17 of which autotests are written.  
  Read more in [CHANGELOG.md](https://github.com/serkonda7/vscode-vba/blob/5b66635c00cee973b16129f6442d1eb9c1fddbf9/CHANGELOG.md)
- Changed internal names of code for better readability
- Closed issue #22
- Fixed typos in the repository

In the second part VBA numeric types #10 will be corrected

2022-04-04 11:13 UTC, bopoh13 commented
_Any comments are welcome_

2022-04-04 11:30 UTC, serkonda7 commented
I can give a review in a few hours.

2022-04-04 12:02 UTC, bopoh13 commented
@serkonda7 please take your time if you get a chance to view. I'm still testing numeric types.

2022-04-04 17:00 UTC, serkonda7 requested changes
Nice work overall :rocket: . I think some pattern names require clarification as stated in the comments.
Please let me know what you think about my suggestions.

The tests (after adapting changed names) look good.

2022-04-04 20:05 UTC, bopoh13 commented
For some reason I couldn't reply under comment.

> Just revert this line

Ok, just the shield looks like button )

> name may be clarified to something like `keyword.procedure.vba`

I wrote `keyword.$1.vba` variant. Will whitespace characters affect autotests?
https://github.com/serkonda7/vscode-vba/blob/15d70fb450432da5c1347243f37029f97a5d37fc/syntaxes/tests/procedure.bas#L4

2022-04-04 21:06 UTC, bopoh13 commented
**Need revise description:** this PR doesn't solve issue #16
Link: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/class-statement

2022-04-04 22:55 UTC, bopoh13 commented
> Replaced description of the first commit in PR. Branch _bopoh13:dev-types_ is broken.

2022-04-05 03:59 UTC, serkonda7 commented
> **Need revise description:** this PR doesn't solve issue #16
> Link: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/class-statement

Sorry, was too fast on this one.

2022-04-05 04:17 UTC, serkonda7 commented
> I wrote `keyword.$1.vba` variant. Will whitespace characters affect autotests?

I'm not sure about this but will validate.

2022-04-05 04:30 UTC, serkonda7 requested changes

2022-04-05 04:30 UTC, serkonda7 commented on syntaxes/vba.tmLanguage.json
>  				{
I can understand you merged the number regexes to shorten them but it was a lot easier to understand their behaviour beforehand.
I'd prefer keeping them separated.

2022-04-05 04:31 UTC, serkonda7 commented
Also the test fails:
```
at [syntaxes/tests/procedure.bas:[18](https://github.com/serkonda7/vscode-vba/runs/5827759924?check_suite_focus=true#step:5:18):18:[20](https://github.com/serkonda7/vscode-vba/runs/5827759924?check_suite_focus=true#step:5:20)]:
  18:   Function foo() As Boolean
                       ^^
  missing required scopes: keyword.As.vba
  actual: source.vba keyword.control.vba


  at [syntaxes/tests/procedure.bas:32:20:28]:
  32: Function withParam(Optional p1 As MyType)
                         ^^^^^^^^
  missing required scopes: storage.modifier.visibility
  actual: source.vba keyword.control.vba
```

2022-04-05 04:55 UTC, bopoh13 commented
> I'd prefer keeping them separated

I missed the idea that there would be a group in the future.

> test fails

Well, I understood my mistake. It was necessary to upgrade from `main` branch.

2022-04-05 05:31 UTC, serkonda7 commented
> I missed the idea that there would be a group in the future.

I don't see a benefit in the group. It's just less readable. 
Or have I missed a point here? 

> Well, I understood my mistake. It was necessary to upgrade from `main` branch.

I may expand the contribution docs with a guide to resolve merge conflicts.

2022-04-05 06:04 UTC, bopoh13 commented
> Or have I missed a point here?

I had a little lost where rebase this branch. When installing dev-expansion I didn't see actual files because missed key `--force`.

> I may expand the contribution docs with a guide to resolve merge conflicts.

I understood, judging by [the сommit](
https://github.com/serkonda7/vscode-vba/pull/38/commits/4c55b8d437c5738830413d2ce61d5c299e4d9e76) earlier even squash worked. Thank you

2022-04-05 06:31 UTC, serkonda7 approved these changes
Thanks for the work and discussion. Really nice changes 🎉

2022-04-05 06:31 UTC, merged

2022-04-05 11:31 UTC, bopoh13 commented
Thanks for the discussion and this project. It may be richer than it seems at first glance.